# Generated by Django 4.2.7 on 2026-05-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="支付流水号",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("processing", "处理中"),
                            ("success", "支付成功"),
                            ("failed", "支付失败"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("bank_card", "银行卡"),
                        ],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="第三方交易号",
                    ),
                ),
                (
                    "callback_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回调时间"
                    ),
                ),
                (
                    "callback_data",
                    models.JSONField(blank=True, default=dict, verbose_name="回调数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="order.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付",
                "verbose_name_plural": "支付",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
