# Generated by Django 4.2.7 on 2026-06-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_coupon_order_discount_amount_order_expires_at_and_more"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="发票抬头")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="税号"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待开具"), ("issued", "已开具")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
            },
        ),
    ]
