# Generated by Django 4.2.7 on 2026-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itinerary_id",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="行程ID"
                    ),
                ),
                ("flight_no", models.CharField(max_length=20, verbose_name="航班号")),
                ("airline", models.CharField(max_length=50, verbose_name="航空公司")),
                (
                    "departure_city",
                    models.CharField(max_length=50, verbose_name="出发城市"),
                ),
                (
                    "arrival_city",
                    models.CharField(max_length=50, verbose_name="到达城市"),
                ),
                ("departure_time", models.DateTimeField(verbose_name="出发时间")),
                ("arrival_time", models.DateTimeField(verbose_name="到达时间")),
                (
                    "cabin_class",
                    models.CharField(max_length=20, verbose_name="舱位等级"),
                ),
                (
                    "seat_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="座位号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "即将出行"),
                            ("in_progress", "行程中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="行程状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "行程",
                "verbose_name_plural": "行程",
                "db_table": "itineraries",
                "ordering": ["-departure_time"],
            },
        ),
    ]
