# Generated by Django 4.2.7 on 2026-05-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("itinerary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itineraries",
                to="order.order",
                verbose_name="订单",
            ),
        ),
    ]
