# Generated by Django 4.2.7 on 2026-06-12 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_bookinggroup_trip_type"),
        ("flight", "0002_flightreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_pricewatch_travelchecklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passenger_name",
                    models.CharField(max_length=50, verbose_name="乘客姓名"),
                ),
                (
                    "passenger_id_card",
                    models.CharField(max_length=18, verbose_name="乘客身份证号"),
                ),
                (
                    "cabin_class",
                    models.CharField(
                        default="economy", max_length=20, verbose_name="舱位"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "候补中"),
                            ("fulfilled", "已兑现"),
                            ("cancelled", "已取消"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="flight.flight",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entry",
                        to="order.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "waitlist_entries",
                "ordering": ["created_at"],
            },
        ),
    ]
