# Generated by Django 4.2.7 on 2026-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_no",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="航班号"
                    ),
                ),
                ("airline", models.CharField(max_length=50, verbose_name="航空公司")),
                (
                    "departure_city",
                    models.CharField(max_length=50, verbose_name="出发城市"),
                ),
                (
                    "arrival_city",
                    models.CharField(max_length=50, verbose_name="到达城市"),
                ),
                ("departure_time", models.DateTimeField(verbose_name="计划起飞时间")),
                ("arrival_time", models.DateTimeField(verbose_name="计划到达时间")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基准票价"
                    ),
                ),
                (
                    "available_seats",
                    models.IntegerField(default=0, verbose_name="剩余可售座位数"),
                ),
                (
                    "total_seats",
                    models.IntegerField(default=0, verbose_name="总座位数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("delayed", "延误"),
                            ("cancelled", "取消"),
                            ("departed", "已起飞"),
                            ("landed", "已降落"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="航班状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "航班",
                "verbose_name_plural": "航班",
                "db_table": "flights",
                "ordering": ["departure_time"],
            },
        ),
    ]
