# Generated by Django 4.2.7 on 2026-05-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="订单号"
                    ),
                ),
                (
                    "cabin_class",
                    models.CharField(
                        choices=[
                            ("economy", "经济舱"),
                            ("business", "商务舱"),
                            ("first", "头等舱"),
                        ],
                        default="economy",
                        max_length=20,
                        verbose_name="舱位等级",
                    ),
                ),
                (
                    "seat_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="座位号"
                    ),
                ),
                (
                    "passenger_name",
                    models.CharField(max_length=50, verbose_name="乘客姓名"),
                ),
                (
                    "passenger_id_card",
                    models.CharField(max_length=18, verbose_name="乘客身份证号"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单总金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("ticketed", "已出票"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "ticketed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="出票时间"
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="flight.flight",
                        verbose_name="航班",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
