# Generated by Django 4.2.7 on 2026-06-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_coupon_order_discount_amount_order_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="insurance_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="延误险金额"
            ),
        ),
    ]
