# Generated by Django 4.2.7 on 2026-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_insurance_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinggroup",
            name="trip_type",
            field=models.CharField(
                choices=[
                    ("one_way", "单程"),
                    ("round_trip", "往返"),
                    ("transfer", "中转"),
                    ("multi_city", "多程"),
                ],
                default="one_way",
                max_length=20,
                verbose_name="行程类型",
            ),
        ),
    ]
