# Generated by Django 4.2.7 on 2026-06-12 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentPassenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("id_card", models.CharField(max_length=18, verbose_name="身份证号")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=11, verbose_name="手机号"
                    ),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="默认")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "db_table": "frequent_passengers",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
