# Generated by Django 4.2.7 on 2026-06-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_frequentpassenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.IntegerField(default=0, verbose_name="积分"),
        ),
    ]
